In [1]:
import pandas as pd

In [2]:
path = '210929_tess_5min_24h'

In [3]:
hce_bids = pd.read_csv(path + '/hce_bids.csv', index_col=0, parse_dates=True)
hce_bids['start_time'].iloc[0]

'2021-09-22 00:00:00'

In [4]:
transformer_interval = pd.read_csv(path + '/transformer_intervals.csv', index_col=0, parse_dates=True)

In [5]:
meter_interval = pd.read_csv(path + '/meter_intervals.csv', index_col=0, parse_dates=True)
meter_interval

,meter_id,rate_id,start_time,end_time,e,qmtp,p_bid,q_bid,is_bid,mode_dispatch,mode_market
meter_interval_id,,,,,,,,,,,
1,1,1,2021-09-22 00:00:00,2021-09-22 00:05:00,0.0,0.0,0,0.0,1,1,1
2,2,1,2021-09-22 00:00:00,2021-09-22 00:05:00,0.0,0.0,0,0.0,1,1,1
3,3,1,2021-09-22 00:00:00,2021-09-22 00:05:00,0.0,0.0,0,0.0,1,1,1
4,4,1,2021-09-22 00:00:00,2021-09-22 00:05:00,0.0,0.0,0,0.0,1,1,1
5,5,1,2021-09-22 00:00:00,2021-09-22 00:05:00,0.0,0.0,0,0.0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
1722,2,1,2021-09-23 00:00:00,2021-09-23 00:05:00,0.0,0.0,0,0.0,1,1,1
1723,3,1,2021-09-23 00:00:00,2021-09-23 00:05:00,0.0,0.0,0,0.0,1,1,1
1724,4,1,2021-09-23 00:00:00,2021-09-23 00:05:00,0.0,0.0,0,0.0,1,1,1
1725,5,1,2021-09-23 00:00:00,2021-09-23 00:05:00,0.0,0.0,0,0.0,1,1,1
1726,6,1,2021-09-23 00:00:00,2021-09-23 00:05:00,0.0,0.0,0,0.0,1,1,1

In [35]:
market = pd.read_csv(path + '/markets.csv', index_col=0, parse_dates=True).iloc[:1]
market_interval = pd.read_csv(path + '/market_intervals.csv', index_col=0, parse_dates=True)
market

,source,ts,p_max,is_active,is_archived,updated_at,created_at
market_id,,,,,,,
1,Ercot,300,10000,0,0,2021-09-24 20:28:54,NaN

In [7]:
p_clear = list(market_interval["p_clear"])
p_clear

[0.81,
 0.09,
 0.28,
 0.39,
 0.96,
 0.74,
 0.87,
 0.15,
 0.88,
 0.68,
 0.35,
 0.38,
 0.01,
 0.02,
 0.32,
 0.32,
 0.93,
 0.15,
 0.19,
 0.37,
 0.4,
 0.31,
 0.97,
 0.6,
 0.16,
 0.08,
 1.0,
 0.3,
 0.74,
 0.03,
 0.36,
 0.65,
 0.88,
 0.33,
 0.18,
 0.63,
 0.61,
 0.54,
 0.39,
 0.4,
 0.46,
 0.48,
 0.69,
 0.64,
 0.98,
 0.09,
 0.8,
 0.42,
 0.05,
 0.68,
 0.57,
 0.6,
 0.19,
 0.22,
 0.13,
 0.78,
 0.61,
 0.49,
 0.61,
 0.32,
 0.06,
 0.25,
 0.4,
 0.34,
 0.41,
 0.14,
 0.62,
 0.41,
 0.85,
 0.47,
 0.09,
 0.66,
 0.46,
 0.59,
 0.67,
 0.72,
 0.04,
 0.19,
 0.77,
 0.08,
 0.06,
 0.46,
 0.44,
 0.75,
 0.17,
 0.51,
 0.18,
 0.61,
 0.44,
 0.79,
 0.12,
 0.68,
 0.75,
 0.05,
 0.49,
 0.06,
 0.92,
 0.47,
 0.09,
 0.36,
 0.58,
 0.71,
 0.55,
 0.38,
 0.71,
 0.04,
 0.66,
 0.61,
 0.33,
 0.75,
 0.32,
 0.5,
 0.12,
 0.62,
 0.9,
 0.9,
 0.21,
 0.35,
 0.93,
 0.68,
 0.24,
 0.59,
 0.38,
 0.64,
 0.88,
 0.28,
 0.78,
 0.3,
 0.28,
 0.3,
 0.89,
 0.83,
 0.15,
 0.34,
 0.59,
 0.26,
 0.29,
 0.08,
 0.96,
 0.68,
 0.2,
 0.93,
 0.81,
 0.95,
 0.54,
 0.01,
 0.72,
 0.71,
 0.71,
 0.91,
 0.93,
 0.59,
 0.13,
 0.75,
 0.22,
 0.68,
 0.45,
 0.15,
 0.19,
 0.81,
 0.45,
 0.63,
 0.1,
 0.61,
 0.94,
 0.06,
 0.78,
 0.78,
 0.82,
 0.48,
 0.27,
 0.31,
 0.23,
 0.85,
 0.17,
 0.51,
 0.12,
 0.63,
 0.27,
 0.69,
 0.61,
 0.17,
 0.26,
 0.55,
 0.65,
 0.24,
 0.78,
 0.81,
 0.87,
 0.72,
 0.34,
 0.41,
 0.65,
 0.32,
 0.3,
 0.06,
 0.5,
 0.37,
 0.29,
 0.82,
 0.12,
 0.48,
 0.47,
 0.87,
 0.78,
 0.09,
 0.09,
 0.42,
 0.6,
 0.53,
 0.38,
 0.07,
 0.6,
 0.71,
 0.43,
 0.02,
 0.44,
 0.44,
 0.4,
 0.36,
 0.17,
 0.94,
 0.89,
 0.04,
 0.1,
 0.62,
 0.21,
 0.19,
 0.83,
 0.45,
 0.82,
 0.84,
 0.94,
 0.44,
 0.39,
 0.04,
 0.09,
 0.19,
 0.53,
 0.51,
 0.44,
 0.65,
 0.18,
 0.99,
 0.87,
 0.21,
 0.68,
 0.3,
 0.0,
 0.72,
 0.83,
 0.77,
 0.01,
 0.47,
 0.93,
 0.82,
 0.11,
 0.65,
 0.41,
 0.15,
 0.37,
 0.58,
 0.58,
 0.49,
 0.28,
 0.45,
 0.7,
 0.29,
 0.4,
 0.23,
 0.6,
 0.05,
 0.08,
 0.59,
 0.04,
 0.14,
 0.19,
 0.09,
 0.4,
 0.57,
 0.8]

## Choose period for which cash flow should be calculated

In [8]:
market_id = 1
start_time = '2021-09-22 12:00:00'

## 1 ) Payments from retail income

In [36]:
RR = 0.20 # hard-coded, need to check
interval = market.loc[market_id]['ts']
unresp_load = transformer_interval['unresp_load'].loc[transformer_interval['start_time'] == start_time].iloc[-1]
retail_income = RR*unresp_load*interval/3600. # price*energy
interval

300

## 2) Payments to WS supply

In [39]:
import_power = transformer_interval['q'].loc[transformer_interval['start_time'] == start_time].iloc[-1]
mc_WS = hce_bids['p_bid'].loc[(hce_bids['start_time'] == start_time) & (hce_bids['comment'] == 'import')].iloc[-1]
import_expenses = mc_WS*import_power*interval/3600. # price*energy
import_expenses

0.2980441095833333

## 3) PAYMENTS TO PV OWNERS: Sum all ((qmtp in TABLE meter_intervals for which p_bid <= p_clear))*p_clear

In [11]:
bids = meter_interval.loc[meter_interval['start_time'] == start_time]
bids

,meter_id,rate_id,start_time,end_time,e,qmtp,p_bid,q_bid,is_bid,mode_dispatch,mode_market
meter_interval_id,,,,,,,,,,,
865,1,1,2021-09-22 12:00:00,2021-09-22 12:05:00,0.034029,0.408345,0,0.408345,1,1,1
866,2,1,2021-09-22 12:00:00,2021-09-22 12:05:00,0.043590,0.523077,0,0.523077,1,1,1
867,3,1,2021-09-22 12:00:00,2021-09-22 12:05:00,0.042545,0.510540,0,0.510540,1,1,1
868,4,1,2021-09-22 12:00:00,2021-09-22 12:05:00,0.039947,0.479368,0,0.479368,1,1,1
869,5,1,2021-09-22 12:00:00,2021-09-22 12:05:00,0.047694,0.572327,0,0.572327,1,1,1
870,6,1,2021-09-22 12:00:00,2021-09-22 12:05:00,0.044687,0.536243,0,0.536243,1,1,1

In [38]:
# Get clearing price for each bid for later comparison at time t
bids_interval = bids.merge(market_interval, on="start_time", how="left")
assert len(bids) == len(bids_interval) # should not increase no of rows

In [24]:
cleared_bids = bids_interval.loc[bids_interval.p_bid <= bids_interval.p_clear]
cleared_bids

,meter_id,rate_id,start_time,end_time_x,e,qmtp,p_bid,q_bid,is_bid,mode_dispatch,mode_market,market_id,p_exp,p_dev,p_clear,q_clear,alpha,end_time_y
0,1,1,2021-09-22 12:00:00,2021-09-22 12:05:00,0.034029,0.408345,0,0.408345,1,1,1,1,0.474722,0.076271,0.54,9.645,1,2021-09-22 12:05:00
1,2,1,2021-09-22 12:00:00,2021-09-22 12:05:00,0.043590,0.523077,0,0.523077,1,1,1,1,0.474722,0.076271,0.54,9.645,1,2021-09-22 12:05:00
2,3,1,2021-09-22 12:00:00,2021-09-22 12:05:00,0.042545,0.510540,0,0.510540,1,1,1,1,0.474722,0.076271,0.54,9.645,1,2021-09-22 12:05:00
3,4,1,2021-09-22 12:00:00,2021-09-22 12:05:00,0.039947,0.479368,0,0.479368,1,1,1,1,0.474722,0.076271,0.54,9.645,1,2021-09-22 12:05:00
4,5,1,2021-09-22 12:00:00,2021-09-22 12:05:00,0.047694,0.572327,0,0.572327,1,1,1,1,0.474722,0.076271,0.54,9.645,1,2021-09-22 12:05:00
5,6,1,2021-09-22 12:00:00,2021-09-22 12:05:00,0.044687,0.536243,0,0.536243,1,1,1,1,0.474722,0.076271,0.54,9.645,1,2021-09-22 12:05:00

In [23]:
cleared_bids["payments_to_pv_owner"] = cleared_bids["p_clear"]*cleared_bids["q_bid"]*interval/3600.

In [21]:
payments_to_pv_owners = cleared_bids["payments_to_pv_owner"].sum()
payments_to_pv_owners

0.1363455

## 4) retail income MINUS import costs MINUS payments to PV owners â†’ THIS IS WHAT GETS PLOTTED

In [22]:
retail_income - import_expenses - payments_to_pv_owners # cash flow / net revenue at time t

-0.27363644291666667

In [31]:
start_times = transformer_interval["start_time"].unique()

In [32]:
start_times

array(['2021-09-22 00:00:00', '2021-09-22 00:05:00',
       '2021-09-22 00:10:00', '2021-09-22 00:15:00',
       '2021-09-22 00:20:00', '2021-09-22 00:25:00',
       '2021-09-22 00:30:00', '2021-09-22 00:35:00',
       '2021-09-22 00:40:00', '2021-09-22 00:45:00',
       '2021-09-22 00:50:00', '2021-09-22 00:55:00',
       '2021-09-22 01:00:00', '2021-09-22 01:05:00',
       '2021-09-22 01:10:00', '2021-09-22 01:15:00',
       '2021-09-22 01:20:00', '2021-09-22 01:25:00',
       '2021-09-22 01:30:00', '2021-09-22 01:35:00',
       '2021-09-22 01:40:00', '2021-09-22 01:45:00',
       '2021-09-22 01:50:00', '2021-09-22 01:55:00',
       '2021-09-22 02:00:00', '2021-09-22 02:05:00',
       '2021-09-22 02:10:00', '2021-09-22 02:15:00',
       '2021-09-22 02:20:00', '2021-09-22 02:25:00',
       '2021-09-22 02:30:00', '2021-09-22 02:35:00',
       '2021-09-22 02:40:00', '2021-09-22 02:45:00',
       '2021-09-22 02:50:00', '2021-09-22 02:55:00',
       '2021-09-22 03:00:00', '2021-09-22 03:05:00',
       '2021-09-22 03:10:00', '2021-09-22 03:15:00',
       '2021-09-22 03:20:00', '2021-09-22 03:25:00',
       '2021-09-22 03:30:00', '2021-09-22 03:35:00',
       '2021-09-22 03:40:00', '2021-09-22 03:45:00',
       '2021-09-22 03:50:00', '2021-09-22 03:55:00',
       '2021-09-22 04:00:00', '2021-09-22 04:05:00',
       '2021-09-22 04:10:00', '2021-09-22 04:15:00',
       '2021-09-22 04:20:00', '2021-09-22 04:25:00',
       '2021-09-22 04:30:00', '2021-09-22 04:35:00',
       '2021-09-22 04:40:00', '2021-09-22 04:45:00',
       '2021-09-22 04:50:00', '2021-09-22 04:55:00',
       '2021-09-22 05:00:00', '2021-09-22 05:05:00',
       '2021-09-22 05:10:00', '2021-09-22 05:15:00',
       '2021-09-22 05:20:00', '2021-09-22 05:25:00',
       '2021-09-22 05:30:00', '2021-09-22 05:35:00',
       '2021-09-22 05:40:00', '2021-09-22 05:45:00',
       '2021-09-22 05:50:00', '2021-09-22 05:55:00',
       '2021-09-22 06:00:00', '2021-09-22 06:05:00',
       '2021-09-22 06:10:00', '2021-09-22 06:15:00',
       '2021-09-22 06:20:00', '2021-09-22 06:25:00',
       '2021-09-22 06:30:00', '2021-09-22 06:35:00',
       '2021-09-22 06:40:00', '2021-09-22 06:45:00',
       '2021-09-22 06:50:00', '2021-09-22 06:55:00',
       '2021-09-22 07:00:00', '2021-09-22 07:05:00',
       '2021-09-22 07:10:00', '2021-09-22 07:15:00',
       '2021-09-22 07:20:00', '2021-09-22 07:25:00',
       '2021-09-22 07:30:00', '2021-09-22 07:35:00',
       '2021-09-22 07:40:00', '2021-09-22 07:45:00',
       '2021-09-22 07:50:00', '2021-09-22 07:55:00',
       '2021-09-22 08:00:00', '2021-09-22 08:05:00',
       '2021-09-22 08:10:00', '2021-09-22 08:15:00',
       '2021-09-22 08:20:00', '2021-09-22 08:25:00',
       '2021-09-22 08:30:00', '2021-09-22 08:35:00',
       '2021-09-22 08:40:00', '2021-09-22 08:45:00',
       '2021-09-22 08:50:00', '2021-09-22 08:55:00',
       '2021-09-22 09:00:00', '2021-09-22 09:05:00',
       '2021-09-22 09:10:00', '2021-09-22 09:15:00',
       '2021-09-22 09:20:00', '2021-09-22 09:25:00',
       '2021-09-22 09:30:00', '2021-09-22 09:35:00',
       '2021-09-22 09:40:00', '2021-09-22 09:45:00',
       '2021-09-22 09:50:00', '2021-09-22 09:55:00',
       '2021-09-22 10:00:00', '2021-09-22 10:05:00',
       '2021-09-22 10:10:00', '2021-09-22 10:15:00',
       '2021-09-22 10:20:00', '2021-09-22 10:25:00',
       '2021-09-22 10:30:00', '2021-09-22 10:35:00',
       '2021-09-22 10:40:00', '2021-09-22 10:45:00',
       '2021-09-22 10:50:00', '2021-09-22 10:55:00',
       '2021-09-22 11:00:00', '2021-09-22 11:05:00',
       '2021-09-22 11:10:00', '2021-09-22 11:15:00',
       '2021-09-22 11:20:00', '2021-09-22 11:25:00',
       '2021-09-22 11:30:00', '2021-09-22 11:35:00',
       '2021-09-22 11:40:00', '2021-09-22 11:45:00',
       '2021-09-22 11:50:00', '2021-09-22 11:55:00',
       '2021-09-22 12:00:00', '2021-09-22 12:05:00',
       '2021-09-22 12:10:00', '2021-09-22 12:15:00',
       '2021-09-22 12:20:00', '2021-09-22 12:25:00',
       '2021-09-22 12:30:00', '2021-09-22 12:35:00',
       '2021-09-22 12:40:00', '2021-09-22 12:45:00',
       '2021-09-22 12:50:00', '2021-09-22 12:55:00',
       '2021-09-22 13:00:00', '2021-09-22 13:05:00',
       '2021-09-22 13:10:00', '2021-09-22 13:15:00',
       '2021-09-22 13:20:00', '2021-09-22 13:25:00',
       '2021-09-22 13:30:00', '2021-09-22 13:35:00',
       '2021-09-22 13:40:00', '2021-09-22 13:45:00',
       '2021-09-22 13:50:00', '2021-09-22 13:55:00',
       '2021-09-22 14:00:00', '2021-09-22 14:05:00',
       '2021-09-22 14:10:00', '2021-09-22 14:15:00',
       '2021-09-22 14:20:00', '2021-09-22 14:25:00',
       '2021-09-22 14:30:00', '2021-09-22 14:35:00',
       '2021-09-22 14:40:00', '2021-09-22 14:45:00',
       '2021-09-22 14:50:00', '2021-09-22 14:55:00',
       '2021-09-22 15:00:00', '2021-09-22 15:05:00',
       '2021-09-22 15:10:00', '2021-09-22 15:15:00',
       '2021-09-22 15:20:00', '2021-09-22 15:25:00',
       '2021-09-22 15:30:00', '2021-09-22 15:35:00',
       '2021-09-22 15:40:00', '2021-09-22 15:45:00',
       '2021-09-22 15:50:00', '2021-09-22 15:55:00',
       '2021-09-22 16:00:00', '2021-09-22 16:05:00',
       '2021-09-22 16:10:00', '2021-09-22 16:15:00',
       '2021-09-22 16:20:00', '2021-09-22 16:25:00',
       '2021-09-22 16:30:00', '2021-09-22 16:35:00',
       '2021-09-22 16:40:00', '2021-09-22 16:45:00',
       '2021-09-22 16:50:00', '2021-09-22 16:55:00',
       '2021-09-22 17:00:00', '2021-09-22 17:05:00',
       '2021-09-22 17:10:00', '2021-09-22 17:15:00',
       '2021-09-22 17:20:00', '2021-09-22 17:25:00',
       '2021-09-22 17:30:00', '2021-09-22 17:35:00',
       '2021-09-22 17:40:00', '2021-09-22 17:45:00',
       '2021-09-22 17:50:00', '2021-09-22 17:55:00',
       '2021-09-22 18:00:00', '2021-09-22 18:05:00',
       '2021-09-22 18:10:00', '2021-09-22 18:15:00',
       '2021-09-22 18:20:00', '2021-09-22 18:25:00',
       '2021-09-22 18:30:00', '2021-09-22 18:35:00',
       '2021-09-22 18:40:00', '2021-09-22 18:45:00',
       '2021-09-22 18:50:00', '2021-09-22 18:55:00',
       '2021-09-22 19:00:00', '2021-09-22 19:05:00',
       '2021-09-22 19:10:00', '2021-09-22 19:15:00',
       '2021-09-22 19:20:00', '2021-09-22 19:25:00',
       '2021-09-22 19:30:00', '2021-09-22 19:35:00',
       '2021-09-22 19:40:00', '2021-09-22 19:45:00',
       '2021-09-22 19:50:00', '2021-09-22 19:55:00',
       '2021-09-22 20:00:00', '2021-09-22 20:05:00',
       '2021-09-22 20:10:00', '2021-09-22 20:15:00',
       '2021-09-22 20:20:00', '2021-09-22 20:25:00',
       '2021-09-22 20:30:00', '2021-09-22 20:35:00',
       '2021-09-22 20:40:00', '2021-09-22 20:45:00',
       '2021-09-22 20:50:00', '2021-09-22 20:55:00',
       '2021-09-22 21:00:00', '2021-09-22 21:05:00',
       '2021-09-22 21:10:00', '2021-09-22 21:15:00',
       '2021-09-22 21:20:00', '2021-09-22 21:25:00',
       '2021-09-22 21:30:00', '2021-09-22 21:35:00',
       '2021-09-22 21:40:00', '2021-09-22 21:45:00',
       '2021-09-22 21:50:00', '2021-09-22 21:55:00',
       '2021-09-22 22:05:00', '2021-09-22 22:10:00',
       '2021-09-22 22:15:00', '2021-09-22 22:20:00',
       '2021-09-22 22:25:00', '2021-09-22 22:30:00',
       '2021-09-22 22:40:00', '2021-09-22 22:45:00',
       '2021-09-22 22:50:00', '2021-09-22 22:55:00',
       '2021-09-22 23:00:00', '2021-09-22 23:05:00',
       '2021-09-22 23:10:00', '2021-09-22 23:15:00',
       '2021-09-22 23:20:00', '2021-09-22 23:25:00',
       '2021-09-22 23:30:00', '2021-09-22 23:35:00',
       '2021-09-22 23:40:00', '2021-09-22 23:45:00',
       '2021-09-22 23:50:00', '2021-09-22 23:55:00',
       '2021-09-23 00:00:00'], dtype=object)

In [33]:
def get_cash_flow(start_time, transformer_interval, meter_interval, market_interval, hce_bids, market_id=1):
    RR = 0.20 # hard-coded, need to check
    interval = market.loc[market_id]['ts']
    unresp_load = transformer_interval['unresp_load'].loc[transformer_interval['start_time'] == start_time].iloc[-1]
    retail_income = RR*unresp_load*interval/3600. # price*energy
    import_power = transformer_interval['q'].loc[transformer_interval['start_time'] == start_time].iloc[-1]
    mc_WS = hce_bids['p_bid'].loc[(hce_bids['start_time'] == start_time) & (hce_bids['comment'] == 'import')].iloc[-1]
    import_expenses = mc_WS*import_power*interval/3600. # price*energy
    bids = meter_interval.loc[meter_interval['start_time'] == start_time]
    bids_interval = bids.merge(market_interval, on="start_time", how="left")
    assert len(bids) == len(bids_interval) # should not increase no of rows
    cleared_bids = bids_interval.loc[bids_interval.p_bid <= bids_interval.p_clear]
    cleared_bids["payments_to_pv_owner"] = cleared_bids["p_clear"]*cleared_bids["q_bid"]*interval/3600.
    payments_to_pv_owners = cleared_bids["payments_to_pv_owner"].sum()
    return retail_income - import_expenses - payments_to_pv_owners # cash flow / net revenue at time t

cash_flow = []
for time in start_times: 
    cash_flow.append(get_cash_flow(time))

In [34]:
cash_flow

[-0.1363455,
 -0.09911925645833333,
 -0.16260154,
 -0.197122984,
 -0.38490094,
 -0.312917206,
 -0.35594040400000004,
 -0.118460488,
 -0.35857285400000005,
 -0.294404318,
 -0.185167912,
 -0.194099334,
 -0.07402829192000002,
 -0.08091172504166667,
 -0.17335835458333332,
 -0.1745487025,
 -0.36129153625000004,
 -0.12215327125,
 -0.13313666875,
 -0.18925607791666665,
 -0.19963547833333334,
 -0.17156524791666666,
 -0.3760611379166666,
 -0.2597330333333333,
 -0.12307613916666667,
 -0.09924465986666667,
 -0.37587699916666667,
 -0.1664609215,
 -0.2972039161666667,
 -0.0852723818,
 -0.184187264,
 -0.2728591988333333,
 -0.3394751871666667,
 -0.17481245866666667,
 -0.12928407916666668,
 -0.26430624983333334,
 -0.25854965350000003,
 -0.23632793933333335,
 -0.19224489216666668,
 -0.19569527683333332,
 -0.21273102933333332,
 -0.2212416005,
 -0.2828401503333333,
 -0.26763365033333336,
 -0.36995699616666666,
 -0.1040917979,
 -0.3153355463333333,
 -0.20131691116666667,
 -0.0929033919,
 -0.278436966,
 -0.24628097799999998,
 -0.254698584,
 -0.134838216,
 -0.141868036,
 -0.11547000400000001,
 -0.309891462,
 -0.25963644399999997,
 -0.222733912,
 -0.257288502,
 -0.172140068,
 -0.0959036816,
 -0.15098352875,
 -0.19711454125,
 -0.17892837791666666,
 -0.20005186791666668,
 -0.11865436041666669,
 -0.26570334791666667,
 -0.2027975625,
 -0.33779725708333336,
 -0.21870921708333332,
 -0.10265633208333333,
 -0.27930148625000006,
 -0.21737305541666666,
 -0.2678387355,
 -0.2934453270833333,
 -0.31265404983333334,
 -0.08355886636666666,
 -0.13290916916666667,
 -0.32668866466666663,
 -0.09676053716666666,
 -0.088988001925,
 -0.22315389858333332,
 -0.21518376966666664,
 -0.314679219,
 -0.1261245905,
 -0.23562291133333335,
 -0.1252243645,
 -0.25736972908333333,
 -0.20093279333333333,
 -0.30047133966666667,
 -0.10149867933333334,
 -0.2569855968333334,
 -0.27041569733333337,
 -0.07916224851666667,
 -0.19228365608333334,
 -0.08086855103333335,
 -0.2918794180833333,
 -0.1812931611666667,
 -0.08599440425000002,
 -0.14993413008333334,
 -0.19941634533333336,
 -0.227021205,
 -0.18941428050000003,
 -0.14879038949999998,
 -0.21946766816666663,
 -0.07317803793333333,
 -0.20425368933333335,
 -0.19047899999999998,
 -0.13156289166666668,
 -0.3384662008333333,
 -0.12491510400000001,
 -0.15601544275,
 -0.05141321083333335,
 -0.2633507064166667,
 -0.21005292866666667,
 -0.3604054268333333,
 -0.09570651666666667,
 -0.1465562403333333,
 -0.3595745120833333,
 -0.3671563906666667,
 -0.10584688333333332,
 -0.23148861333333337,
 -0.15563551249999996,
 -0.3453647924166667,
 -0.49068085000000006,
 -0.11990444766666665,
 -0.30295380400000005,
 -0.12893663041666664,
 -0.1404976245833333,
 -0.12694446266666667,
 -0.49225896049999995,
 -0.452166856,
 -0.08376801933333335,
 -0.14143956291666665,
 -0.2278961096666667,
 -0.09813518141666666,
 -0.1376113913333333,
 -0.04570662879999998,
 -0.3520600033333333,
 -0.25218959350000003,
 -0.08707402900000001,
 -0.3362452254166667,
 -0.16334357366666669,
 -0.1789661201666667,
 -0.27363644291666667,
 -0.06177876682416668,
 -0.08734148000000001,
 -0.255323158,
 -0.14630455566666667,
 -0.4709662545833333,
 -0.3254753636666667,
 -0.29595381983333335,
 -0.059953157333333326,
 -0.3800744515,
 -0.08631400183333335,
 -0.3421912941666667,
 -0.1677811015,
 -0.07839844741666667,
 -0.081227924,
 -0.15473130208333336,
 -0.21997015466666667,
 -0.13510321933333336,
 -0.053179495333333326,
 -0.3081029723333333,
 -0.17320758125,
 -0.037566948933333344,
 -0.52478297875,
 -0.28017443233333333,
 -0.4291852171666666,
 -0.12196110066666668,
 -0.096473102,
 -0.12487171899999999,
 -0.09229272691666666,
 -0.5934358924166665,
 -0.07139126933333334,
 -0.19841378666666665,
 -0.06282399333333333,
 -0.24408217133333338,
 -0.11426264033333335,
 -0.26657321333333334,
 -0.24085429175,
 -0.0823652855,
 -0.11458235533333334,
 -0.22519881433333333,
 -0.16949107958333334,
 -0.10225743766666666,
 -0.3172742033333333,
 -0.20370470899999998,
 -0.49555799491666663,
 -0.19365854416666664,
 -0.15413476000000004,
 -0.18207896625000003,
 -0.18768445316666665,
 -0.12744047933333336,
 -0.12357939800000002,
 -0.07179143466666667,
 -0.17410435600000002,
 -0.1461590169166667,
 -0.12780118441666666,
 -0.38711275366666664,
 -0.08746828341666667,
 -0.29820089583333337,
 -0.1791675186666667,
 -0.2881985193333333,
 -0.2685891245833334,
 -0.05484715693333332,
 -0.080907349775,
 -0.18360475275,
 -0.2426459933333333,
 -0.22339522933333333,
 -0.17859313875000002,
 -0.07532149053333334,
 -0.259699912,
 -0.3077922356666667,
 -0.2123943413333333,
 -0.056876848016666676,
 -0.21738883,
 -0.20796891791666666,
 -0.1960266796666667,
 -0.18295411425000002,
 -0.11468857575000001,
 -0.41176206,
 -0.39977854141666663,
 -0.06470799306666668,
 -0.09035474393333334,
 -0.30152106900000003,
 -0.13763023750000003,
 -0.129416592,
 -0.39923846966666665,
 -0.24043168250000002,
 -0.393194005,
 -0.4030819656666666,
 -0.44355963,
 -0.234052772,
 -0.21473966766666663,
 -0.06850436193333335,
 -0.08846512100833333,
 -0.13324275291666665,
 -0.2726994055,
 -0.2674566998333333,
 -0.23626403699999998,
 -0.3342469095,
 -0.127337886,
 -0.4817139030000001,
 -0.4274910000000001,
 -0.14024388150000003,
 -0.3452670585000001,
 -0.1809614745,
 -0.05106039273,
 -0.36123903,
 -0.411381531,
 -0.38701697400000007,
 -166.9276995915,
 -100.04725291580667,
 -0.26077823933333333,
 -0.4709013801666667,
 -0.4191549556666666,
 -0.09392081683333334,
 -166.8321403544,
 -100.343953587,
 -0.23308293749999998,
 -0.111663486,
 -0.215294285,
 -0.11915555050000001,
 -16.96917561691667,
 -0.299921538,
 -0.26219742225,
 -0.17006754375,
 -0.24306727574999998,
 -167.0460561045,
 -17.02089616591667,
 -0.17535747975,
 -0.25756526625,
 -66.89134792691668,
 -0.1499295225,
 -0.28255443299999994,
 -0.08217336365,
 -0.09158615445,
 -0.2799232235,
 -0.0770765915,
 -0.114765961,
 -0.157670084,
 -100.13094947866668,
 -0.09727667614999999,
 -0.21086736850000004,
 -0.2741701085,
 -0.35977808549999996]