In [1]:
import pandas as pd

In [4]:
data = pd.read_csv('meter_intervals.csv', index_col=0, parse_dates=True)

In [6]:
hundred_precent = 24000.0

In [5]:
data

,is_bid,mode_dispatch,meter_id,qmtp,start_time,q_bid,end_time,p_bid,mode_market,rate_id,e,meter_interval_id
0,True,0.0,1,0.000,2021-07-22T09:00:00,0.0,2021-07-22T09:01:00,0.0,0.0,1,0.000000,1
1,True,0.0,2,0.000,2021-07-22T09:00:00,0.0,2021-07-22T09:01:00,0.0,0.0,1,0.000000,2
2,True,0.0,3,0.000,2021-07-22T09:00:00,0.0,2021-07-22T09:01:00,0.0,0.0,1,0.000000,3
3,True,0.0,4,0.000,2021-07-22T09:00:00,0.0,2021-07-22T09:01:00,0.0,0.0,1,0.000000,4
4,True,0.0,5,0.000,2021-07-22T09:00:00,0.0,2021-07-22T09:01:00,0.0,0.0,1,0.000000,5
...,...,...,...,...,...,...,...,...,...,...,...,...
2343,True,0.0,1,3.901,2021-09-21T13:04:04,0.0,2021-09-21T13:05:04,0.0,0.0,1,0.325083,2344
2344,True,0.0,1,3.857,2021-09-21T13:09:05,0.0,2021-09-21T13:10:05,0.0,0.0,1,0.321417,2345
2345,True,0.0,1,3.861,2021-09-21T13:14:06,0.0,2021-09-21T13:15:06,0.0,0.0,1,0.321750,2346
2346,True,0.0,1,3.852,2021-09-21T13:19:06,0.0,2021-09-21T13:20:06,0.0,0.0,1,0.321000,2347
2347,True,0.0,1,3.866,2021-09-21T13:24:07,0.0,2021-09-21T13:25:07,0.0,0.0,1,0.322167,2348

In [13]:
data["qmtp"].sum()

2147.41746